# Generated by Django 3.2.4 on 2021-06-10 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_address_a_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(blank=True, max_length=16, null=True)),
                ('t_test', models.CharField(max_length=12)),
                ('t_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.usermodel')),
            ],
        ),
    ]
