# Generated by Django 3.1.3 on 2020-11-10 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESTserializer', '0002_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='p_name',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='student',
            name='s_name',
            field=models.CharField(max_length=16),
        ),
    ]
