# Generated by Django 3.1.1 on 2020-09-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200905_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='p_name',
            field=models.CharField(db_column='name', max_length=16, unique=True),
        ),
    ]
