# Generated by Django 3.1.1 on 2020-09-23 17:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0002_mainnav'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mainnav',
            table='axf_nav',
        ),
    ]
