# Generated by Django 3.1.1 on 2020-09-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0003_auto_20200923_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainMustBuy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=64)),
                ('trackid', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'axf_mustbuy',
            },
        ),
    ]
