# Generated by Django 3.1.1 on 2020-09-25 16:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0007_foodtype'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='foodtype',
            table='axf_foodtype',
        ),
    ]
