# Generated by Django 3.1.1 on 2020-09-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0009_goods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='productimg',
            field=models.CharField(max_length=512),
        ),
    ]
