# Generated by Django 3.1.1 on 2020-09-25 21:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0010_auto_20200925_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='productimg',
            field=models.CharField(max_length=1024),
        ),
    ]
