# Generated by Django 3.1.1 on 2020-10-17 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_users'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='axf_users',
        ),
    ]
