# Generated by Django 3.1.1 on 2020-10-17 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20201017_1631'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='AXFUser',
        ),
    ]
