# Generated by Django 3.1.1 on 2020-10-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20201017_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='axfuser',
            name='u_password',
            field=models.CharField(max_length=128),
        ),
    ]
