# Generated by Django 3.1.1 on 2020-09-15 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('again', '0007_auto_20200915_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idcard',
            name='id_person',
            field=models.OneToOneField(default='123', on_delete=django.db.models.deletion.SET_DEFAULT,
                                       to='again.person'),
        ),
    ]
