# Generated by Django 3.1.1 on 2020-09-15 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('again', '0009_auto_20200915_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idcard',
            name='id_person',
            field=models.OneToOneField(default=7, on_delete=django.db.models.deletion.SET_DEFAULT, to='again.person'),
        ),
    ]
