# Generated by Django 3.1.1 on 2020-09-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('again', '0011_auto_20200915_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idcard',
            name='id_person',
            field=models.OneToOneField(blank=True, null=True, on_delete=models.SET(7), to='again.person'),
        ),
    ]
