# Generated by Django 3.1.1 on 2020-09-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('again', '0013_auto_20200915_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_name', models.CharField(max_length=16)),
                ('g_customer', models.ManyToManyField(to='again.Customer')),
            ],
        ),
    ]
