# Generated by Django 3.1.1 on 2020-09-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('again', '0014_customer_goods'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_name', models.CharField(max_length=16)),
                ('c_eat', models.CharField(max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_name', models.CharField(max_length=16)),
                ('d_legs', models.IntegerField(default=4)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
