# Generated by Django 3.1.1 on 2020-09-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('again', '0015_cat_dog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_name', models.CharField(blank=True, max_length=16, null=True)),
            ],
            options={
                'db_table': 'book',
                'managed': False,
            },
        ),
    ]
