# Generated by Django 3.1.1 on 2020-09-10 00:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('next', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='g_game',
            new_name='g_grade',
        ),
    ]
